# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui',
# licensing of 'mainwindow.ui' applies.
#
# Created: Fri Aug 16 16:16:59 2019
#      by: pyside2-uic  running on PySide2 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(497, 488)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.listView = QtWidgets.QListView(self.centralwidget)
        self.listView.setObjectName("listView")
        self.verticalLayout.addWidget(self.listView)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_2)
        self.number = QtWidgets.QSpinBox(self.centralwidget)
        self.number.setMinimum(1)
        self.number.setMaximum(1000000)
        self.number.setObjectName("number")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.number)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.label_3)
        self.text = QtWidgets.QLineEdit(self.centralwidget)
        self.text.setObjectName("text")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.text)
        self.insert = QtWidgets.QPushButton(self.centralwidget)
        self.insert.setObjectName("insert")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.insert)
        self.update_text = QtWidgets.QLineEdit(self.centralwidget)
        self.update_text.setObjectName("update_text")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.update_text)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(7, QtWidgets.QFormLayout.FieldRole, spacerItem)
        self.update_number = QtWidgets.QSpinBox(self.centralwidget)
        self.update_number.setMinimum(1)
        self.update_number.setMaximum(1000000)
        self.update_number.setObjectName("update_number")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.update_number)
        self.update_button = QtWidgets.QPushButton(self.centralwidget)
        self.update_button.setEnabled(True)
        self.update_button.setObjectName("update_button")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.update_button)
        self.update_form_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.update_form_label.setFont(font)
        self.update_form_label.setObjectName("update_form_label")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.update_form_label)
        self.update_id = QtWidgets.QLabel(self.centralwidget)
        self.update_id.setObjectName("update_id")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.update_id)
        self.gridLayout.addLayout(self.formLayout, 0, 1, 2, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.delete_2 = QtWidgets.QPushButton(self.centralwidget)
        self.delete_2.setObjectName("delete_2")
        self.horizontalLayout.addWidget(self.delete_2)
        self.update = QtWidgets.QPushButton(self.centralwidget)
        self.update.setObjectName("update")
        self.horizontalLayout.addWidget(self.update)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 497, 20))
        self.menubar.setObjectName("menubar")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        mainWindow.setWindowTitle(QtWidgets.QApplication.translate("mainWindow", "ETH contract DB", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("mainWindow", "Input new values:", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("mainWindow", "Number", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("mainWindow", "Text", None, -1))
        self.insert.setText(QtWidgets.QApplication.translate("mainWindow", "Insert", None, -1))
        self.update_button.setText(QtWidgets.QApplication.translate("mainWindow", "Update", None, -1))
        self.update_form_label.setText(QtWidgets.QApplication.translate("mainWindow", "Update form", None, -1))
        self.update_id.setText(QtWidgets.QApplication.translate("mainWindow", "id", None, -1))
        self.delete_2.setText(QtWidgets.QApplication.translate("mainWindow", "Delete selected", None, -1))
        self.update.setText(QtWidgets.QApplication.translate("mainWindow", "Update selected", None, -1))

